<a href="https://colab.research.google.com/github/pedroop23/NumPyNotebooks/blob/master/NumPyBasico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np



# **Criando array**

In [0]:


a = np.array([10,20,30,40])
a


array([10, 20, 30, 40])

In [0]:
type(a)

numpy.ndarray


# **Criando Matriz**

In [0]:

mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#**Indexação**

In [0]:

print(mat[2][2])


9


#**pegando linha e depois coluna inteira**

In [0]:

print(mat[0,:])
print(mat[:,2])

[1 2 3]
[3 6 9]


#**Transposta**

In [0]:

mat.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#**operações basicas com matrizes**

In [0]:

m1= np.array([[1,2], [3,4]])
m2 = np.array([[5,6],[7,8]])
print("Soma:\n ",m1+m2)
print("subtração\n" ,m1-m2)
print("multiplicação:\n",m1*m2)
print("subtração de todos os elementos por uma cte",m1-1)
print("elevando todos os elementos ao quadrado", m1**2)
print(" soma elementos eixo =0", m1.sum(axis=0)) # soma elementos na vertical pra cada coluna
print("soma elementos eixo =1", m1.sum(axis=1)) # soma na horizontal pra cada linha

Soma:
  [[ 6  8]
 [10 12]]
subtração
 [[-4 -4]
 [-4 -4]]
multiplicação:
 [[ 5 12]
 [21 32]]
subtração de todos os elementos por uma cte [[0 1]
 [2 3]]
elevando todos os elementos ao quadrado [[ 1  4]
 [ 9 16]]
 soma elementos eixo =0 [4 6]
soma elementos eixo =1 [3 7]


#**Deletando Elementos Matriz**


In [0]:
a=np.array([[1,2], [3,4],[5,6]])
print(a)
np.delete(a,1,0) # o terceiro argumento é relativo ao eixo, nesse caso ele apagou a sublista de posição 1 em a
print(np.delete(a,0,1))


[[1 2]
 [3 4]
 [5 6]]
[[2]
 [4]
 [6]]


In [0]:
b= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b)
np.delete(b,np.s_[::2],0) # excluindo de 2 em 2 a partir do eixo 0

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 4,  5,  6],
       [10, 11, 12]])

#**Soma dos elementos do array**

In [0]:

m3= np.array([1,2,3,4])
m3.sum()

10

#**Inserção em um Array**

In [0]:
np.insert(m3,1,10) #inserindo no inicio do Arrray

array([ 1, 10,  2,  3,  4])

In [0]:
np.append(m3,[50,60]) #inserindo non fim do array

array([ 1,  2,  3,  4, 50, 60])

In [0]:
print(m3)
np.delete(m3,3) # deleta o elemento da posição especificada

[1 2 3 4]


array([1, 2, 3])


#**Valor minimo e maximo do array**

In [0]:

print(m3.argmax())
print(m3.argmin())

3
0


In [0]:
np.arange(1,10000001).sum(
    
)

50000005000000

#**Repetindo Elementos**

In [0]:
aa= np.array([[1,2], [3,4]])
print(np.repeat(aa,2)) # 2 é o numero de repetições para cada elemento
print(np.repeat(aa,2,0)) # 0 corresponde ao eixo 

[1 1 2 2 3 3 4 4]
[[1 2]
 [1 2]
 [3 4]
 [3 4]]


#**Repetindo Array ao longo de um texto**


In [0]:
r=np.array([1,2,3])
np.tile(r,3) # segundo argumento é o numero de vezes que vai repetir

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

#**Slicing list** 

In [0]:

lista = [20,30,10,40,50]
print(lista[1:3]) #limite superior aberto (não pega o 3, apenas 1 e 2) 
print(lista[::2]) #não especificou o começo nem o fim -> começa do 0 e pula  duas posições(::2) 

[30, 10]
[20, 10, 50]


#**Slicing Arrays** 

In [0]:

a= np.array(lista)
print(a[1:3])
print(a[::2])

[30 10]
[20 10 50]


#**Dividindo um Array**


In [0]:
r= np.array([[1,2,3],[4,5,6]])
print(np.split(r,2,axis=0)) # 0 corta por uma linha horizontal


[array([[1, 2, 3]]), array([[4, 5, 6]])]


#**Armazenando um Array Dividido**


In [0]:
b= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arrays = np.split(b,2,axis=0)
for array in arrays:
  print(array)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


#**Criando Arrays de zeros e uns**


In [0]:
print(np.zeros((5,5)))
print(np.ones((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#**Cirando Matriz Identidade**

In [0]:
d = np.eye(4)


#**Indexação Booleana**


In [0]:
t = np.array([[1,2],[3,4],[5,6]])
print(t[t>3])
print(t[t>1])

[4 5 6]
[2 3 4 5 6]


#**Diferença lista e array np**


In [0]:
l2 = lista[:]
print ('l2:',l2) 
print('l:', lista)
l2[0] =1000
print ('l2 depois:',l2) # é feita uma copia,alterar l2 não interfere em lista
print('l depois:', lista)

l2: [20, 30, 10, 40, 50]
l: [20, 30, 10, 40, 50]
l2 depois: [1000, 30, 10, 40, 50]
l depois: [20, 30, 10, 40, 50]


In [0]:
b = a[:]
print('antes a:', a )
print ('antes b:',b)
b[0] =1000
print('depois a:', a) #não é feita uma copia como ocorre em list, é uma referencia
print('depois b:', b)

antes a: [20 30 10 40 50]
antes b: [20 30 10 40 50]
depois a: [1000   30   10   40   50]
depois b: [1000   30   10   40   50]


# **Aplicação matriz NP**

In [0]:
joao_pts = [20,30,40,15]
pedro_pts =[100,32,48,23]
maria_pts = [15,90,45,54]
pontos = np.array([joao_pts,pedro_pts,maria_pts])
pontos

array([[ 20,  30,  40,  15],
       [100,  32,  48,  23],
       [ 15,  90,  45,  54]])

#**Uso de alguns métodos de NP com matrizes**


In [0]:
my_data= np.arange(0,20) #valores uniformementes espaçados dentro do intervalo dado (20 n conta)
print(my_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [0]:
mat1= np.reshape(my_data,(5,4)) # o segundo parametro é uma tupla que representa a dimensão da matriz
print(mat1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [0]:
pontos.item(5) #acessa o elemento da posição desejada

32

#**Carregando dados do arquivo**

In [0]:
val1,val2,val3 = np.loadtxt('dados.txt', skiprows=1, unpack= True) # unpack garante que os valores vão ser colocados nas variaveis
print(val1) # primeira coluna
print(val2) #segunda coluna
print(val3) #terceira coluna

[0.1212 0.104  0.5661 0.762 ]
[0.842    0.5422   0.932    0.847361]
[0.3672  0.34551 0.2344  0.1538 ]


In [0]:
meu_array = np.genfromtxt('dados2.txt', skip_header=1, unpack= True, filling_values =-999) 
# filling values preenche valores que faltam
print(meu_array)

[[ 1.21200e-01 -9.99000e+02  5.66100e-01  7.62000e-01]
 [ 8.42000e-01  5.42200e-01  9.32000e-01  8.47361e-01]
 [ 3.67200e-01  3.45510e-01 -9.99000e+02  1.53800e-01]]


#**Concatenando Arrays**

In [0]:
meuarray1 = np.array([[1,2],[3,4]])
meuarray2 = np.array([[5,6]])
print('concatenado pelo eixo 0:',np.concatenate((meuarray1,meuarray2), axis=0)) #pelo eixo 0 ficam 3 duplas
 #faz a transposta da segunda para que ela tenha o mesmo número de colunas que o de linhas da primeira
print('concatenado pelo eixo 1:',np.concatenate((meuarray1,meuarray2.T), axis=1)) #só é possivel fazer pelo eixo 1 nesse caso transpondo a segunda matriz

concatenado pelo eixo 0: [[1 2]
 [3 4]
 [5 6]]
concatenado pelo eixo 1: [[1 2 5]
 [3 4 6]]


#**Embaralhando Arrays**

In [0]:
meuarray3 = np.arange(10)
print(meuarray3)
np.random.shuffle(meuarray3)
print('Depois: ',meuarray3)

[0 1 2 3 4 5 6 7 8 9]
Depois:  [3 1 9 8 2 7 5 4 0 6]


#**Números complexos com NumPy**


In [0]:
ex= np.array([1,10 + 2j, 20+5j])
print(ex)
print(ex[1]+ex[2])

[ 1.+0.j 10.+2.j 20.+5.j]
(30+7j)


# **Gerando Array com linspace**



In [0]:
np.linspace(2.0,3.0, 15) #gera 15 numeros de 2 a 3 uniformemente espaçados, caso o ultimo paramêtro não seja definido, ele gera 50 números por default

array([2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429,
       2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714,
       2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ])

# **Encontrando elementos únicos de um array**


In [0]:
meuArray4 = np.array([[1,2],[2,3],[3,3],[4,4]])
np.unique(meuArray4)

array([1, 2, 3, 4])

#**Lendo arquivos CSV com NumPy**




In [0]:
valores = np.genfromtxt("arquivo.csv", delimiter= ",", skip_header=1) #usar delimitador que é presente no arquivo
print(valores)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]
 [34. 54. 23.]]
